---
- name: PAN-OS Syslog Add
  hosts: PA
  connection: local
  gather_facts: false
  vars_prompt:

    - name: ip
      prompt: "Enter the firewall Mgmt Address or hostname?"
      private: no

    - name: username
      prompt: "Enter the username"
      private: no

    - name: password
      prompt: "Enter the password"

    - name: profile_input
      prompt: "Enter the Profile name"
      private: no

    - name: name_input
      prompt: "Enter the Server name"
      private: no

    - name: port_input 
      prompt: "Enter the port"
      private: no

    - name: ip_input
      prompt: "Enter the Server Address"
      private: no

    - name: format_input
      prompt: "Enter the Log Format (BSD/IETF)"
      private: no

    - name: protocol_input
      prompt: "Enter the Protocol (TCP/UDP/SSL)"
      private: no

    - name: level_input
      prompt: "Enter the facility level (e.q LOG_USER , LOG_LOCAL0-7)"
      private: no

  tasks:

     - name: add new syslog server
       panos_set:
         ip_address: "{{ ip | ipaddr }}"
         username: "{{ username }}"
         password: "{{ password }}"
         xpath:    "/config/shared/log-settings/syslog/entry[@name='{{profile_input}}']/server/entry[@name='{{name_input}}']"
         element:  "<port>{{port_input}}</port><server>{{ip_input | ipaddr}}</server><format>{{format_input}}</format><transport>{{protocol_input}}</transport><facility>{{level_input}}</facility>"
       
     - name: Commit configuration
       panos_commit:
         ip_address: "{{ ip }}"
         username: "{{ username }}"
         password: "{{ password }}"
